{% set name = "healpy" %}
{% set version = "1.12.1" %}
{% set sha256 = "e329ed3f11b99ae83e5d0fbab28f7114a58fd7a364fb3b8a5ff8c71c0d623055" %}

package:
    name: {{ name|lower }}
    version: {{version}}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt
    skip: True  # [win]

requirements:
    build:
        - pkg-config
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
        - numpy        # [py27]
        - numpy        # [py35]
        - numpy         # [py36]
        - pytest-runner
    run:
        - python
        - matplotlib
        - {{ pin_compatible('numpy') }}   # [py27]
        - {{ pin_compatible('numpy') }}   # [py35]
        - {{ pin_compatible('numpy') }}   # [py36]
        - six
        - astropy
        - scipy
        - pytest-runner

test:
    imports:
        - healpy
        - healpy.test
    requires:
        - pytest
        - nose

about:
    home: http://github.com/healpy
    license: GPL-2.0
    summary: Healpix tools package for Python

extra:
    recipe-maintainers:
        - lpsinger
        - mwcraig
        - pkgw
        - zonca
