{% set name = "healpy" %}
{% set version = "1.19.0" %}
{% set sha256 = "28e839cb885a23d36c77fc3423a3cb9271a07fda94085bd12fc329f941130ec5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - macos-c++-linking.patch    # [osx]
    - cross-rpath-flag-workaround.patch  # [aarch64]

build:
  number: 0
  skip: true  # [win or py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - openssl
    - libopenssl-static
    - libtool  # [unix]
    - make  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cfitsio
    - cython
    - python
    - setuptools
    - setuptools-scm
    - numpy
    - pip
    - zlib
  run:
    - python
    - matplotlib-base
    - astropy-base
    - scipy

test:
  source_files:
    - test
    - setup.py
  imports:
    - healpy
  requires:
    - pytest
    - pytest-cython
    - pytest-doctestplus
    - requests
  commands:
    - pytest --doctest-plus --doctest-cython --pyargs healpy
    - pytest test

about:
  home: http://github.com/healpy
  license: GPL-2.0-only
  license_file: COPYING
  summary: Healpix tools package for Python
  doc_url: http://healpy.readthedocs.org/
  dev_url: http://github.com/healpy/healpy

extra:
  recipe-maintainers:
    - lpsinger
    - mwcraig
    - pkgw
    - zonca
