{% set name = "healpy" %}
{% set version = "1.12.4" %}
{% set sha256 = "dff1748b420065290a12ae87ca80f18df8ceefc65563315fc2667a67604a2b70" %}

package:
    name: {{ name|lower }}
    version: {{version}}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1000
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    skip: True  # [win]

requirements:
    build:
        - pkg-config
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
        - numpy
        - pip
        - pytest-runner
        - six
    run:
        - python
        - matplotlib
        - {{ pin_compatible('numpy') }}
        - six
        - astropy
        - scipy
        - pytest-runner

test:
    imports:
        - healpy
        - healpy.test
    requires:
        - pytest
        - nose

about:
    home: http://github.com/healpy
    license: GPL-2.0
    summary: Healpix tools package for Python

extra:
    recipe-maintainers:
        - lpsinger
        - mwcraig
        - pkgw
        - zonca
