appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OoEpz+CAHR4LyM3cEWb4Lt+TufKPEzZ0+VdyGXPoErrvW1hcWQeNaPMRQnr6ML72HHJcrIhZ80IzUquPCz+oZKF1mPuLcKnP2K73KHIU6IyqidgcSjbxx6T1ZjbQm4cWuRcdhuUnMWdDdVwJslnK7OKRHIQG2Mhz8ftysbMvaAwTswifVzBq8pAhL8zIVzd2PVdzKvDPue3t99560cRw4awHdFuqMHywGScQx52Xeh4crlbfAqoteplKCdtoGpO3eSuqzQtMetMqKFfsSiEMYSfHYvTjjEdpoe77/UJn0yoX8uAo6ExaV7IpKLX6knWa9CNRqQzYT3U+XxjAxwhT9hmytcYNt+HeYrKZ3RoHcyS47jfWCdbr8YysQ4+6MP2N30NAQK+1Op64MvPudQP6gofY7MY8ZKkWpVmnoVr0RP7cFm/2vz+QMvPVV7lzrDZdSUusxsDzIvXnNOiNlrdX5ogtTzxPjhWkZJssJ1g9HwDXtyn5AwVT9DH/AhF86kp7nMlnxUx5FDbD+GKGu37YFxuGjQCKKqJp2pj+coTrSu5DbarFecYmNj6UShTC74oXaJ28xM9h51Lqhp8+jVzn0thjPNKhd7U3cq5whG/5/zC+Bh6oQ24mmHG6lKNcGxJTdbuloqOAxtcu38MphXGDyLQP41UTnj430p66bYeJxAc=}
